name: Main

on:

  repository_dispatch:
    types: [build] 

  # Cron Schedule
  schedule:
    - cron: "5 * * * *"

  # On push
  #push:
    # branches: [ main ]
  
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Check Unix Scripts Directory
        id: CheckUnixScripts
        working-directory: ./UnixScripts
        run: |
          if [ -z "$(ls)" ]; then
              echo "Empty"
              echo '::set-output name=num::0'
          else
              echo "Not Empty"
              echo '::set-output name=num::1'
          fi

