name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Check Unix Scripts Directory
        id: CheckUnixScripts
        working-directory: ./UnixScripts
        run: |
          if [ -z "$(ls)" ]; then
              echo "Empty"
              echo '::set-output name=num::0'
          else
              echo "Not Empty"
              echo '::set-output name=num::1'
          fi

      - name: Overwrite Files & Directories
        id: OverwriteFiles1
        if: steps.CheckUnixScripts.outputs.num == 1
        run: |
          mkdir -p Backup
          echo "test" > help.txt
          git config --global user.email "yasmine.hines@aa.com"
          git config --global user.name "yasminehines"
          git add --all Backup/
              
      - name: Overwrite Files & Directories Part 2
        id: OverwriteFiles2
        run: |
          cd ./Backup
          ls -R
          echo "Files and Directories overwritten/moved."
          echo '::set-output name=num::0'

      # extract artifacts from dev
      # - name: Extracts Artifacts
      #   if: steps.CheckUnixScripts.outputs.num == 0 || steps.OverwriteFiles2.outputs.num == 0
      #   # run: |
      #   #   echo "Extracting artifacts from dev" 
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: my-artifact
      #   # path of artifacts from dev
      #     path: ./artifacts
      #     if-no-files-found: warn