name: Slack Notification Demo
on:

  push:
   branches:
    - dev

  # pull_request:
  #   branches:
  #     - main

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: test-githubactions-connection
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff
          SLACK_ICON: 'https://github.githubassets.com/images/modules/logos_page/Octocat.png'
          SLACK_MESSAGE: 'Test worked! :rocket:'
          SLACK_TITLE: Test Slack Notification
          SLACK_USERNAME: GitHub_actions_slackbot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    #   if: always() # Pick up events even if the job fails or is cancelled.
    # steps:
    #   - uses: 8398a7/action-slack@v3
    #     with:
    #       status: custom
    #       fields: workflow,job,commit,repo,ref,author,took
    #       custom_payload: |
    #         {
    #           attachments: [{
    #             color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
    #             text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
    #           }]
    #         }
    #     env:
    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    #     if: always() # Pick up events even if the job fails or is canceled.
